# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/kminilte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/kminilte/proprietary/csc/sales_code.dat:system/csc/sales_code.dat \
    vendor/samsung/kminilte/proprietary/lib/libcsc.so:system/lib/libcsc.so \
    vendor/samsung/kminilte/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
    vendor/samsung/kminilte/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
    vendor/samsung/kminilte/proprietary/lib/libexynosfimc.so:system/lib/libexynosfimc.so \
    vendor/samsung/kminilte/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/kminilte/proprietary/vendor/firmware/bcm4334.hcd:system/vendor/firmware/bcm4334.hcd \
    vendor/samsung/kminilte/proprietary/vendor/firmware/BT_FW_VER_BCM4334B0_002.001.013.1792.1803_K_Mini.hcd:system/vendor/firmware/BT_FW_VER_BCM4334B0_002.001.013.1792.1803_K_Mini.hcd \
    vendor/samsung/kminilte/proprietary/lib/hw/camera.universal3470.so:system/lib/hw/camera.universal3470.so \
    vendor/samsung/kminilte/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/kminilte/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/kminilte/proprietary/lib/libliveframework.so:system/lib/libliveframework.so \
    vendor/samsung/kminilte/proprietary/lib/libarcsoft_nighthawk.so:system/lib/libarcsoft_nighthawk.so \
    vendor/samsung/kminilte/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/kminilte/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/samsung/kminilte/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/kminilte/proprietary/lib/libstagefright_hdcp.so:system/lib/libstagefright_hdcp.so \
    vendor/samsung/kminilte/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/samsung/kminilte/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/samsung/kminilte/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/samsung/kminilte/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/kminilte/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/kminilte/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/kminilte/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/kminilte/proprietary/etc/gps.xml:system/etc/gps.xml \
    vendor/samsung/kminilte/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/kminilte/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/kminilte/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/kminilte/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/kminilte/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/kminilte/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/samsung/kminilte/proprietary/lib/libExynosIPService.so:system/lib/libExynosIPService.so \
    vendor/samsung/kminilte/proprietary/vendor/lib/hw/hwcomposer.exynos3.so:system/vendor/lib/hw/hwcomposer.exynos3.so \
    vendor/samsung/kminilte/proprietary/lib/hw/gralloc.exynos3.so:system/lib/hw/gralloc.exynos3.so \
    vendor/samsung/kminilte/proprietary/lib/libdisplay.so:system/lib/libdisplay.so \
    vendor/samsung/kminilte/proprietary/lib/libdisplaymodule.so:system/lib/libdisplaymodule.so \
    vendor/samsung/kminilte/proprietary/lib/libExynosHWCService.so:system/lib/libExynosHWCService.so \
    vendor/samsung/kminilte/proprietary/lib/libhdmimodule.so:system/lib/libhdmimodule.so \
    vendor/samsung/kminilte/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/kminilte/proprietary/lib/libhwcutils.so:system/lib/libhwcutils.so \
    vendor/samsung/kminilte/proprietary/lib/libvirtualdisplaymodule.so:system/lib/libvirtualdisplaymodule.so \
    vendor/samsung/kminilte/proprietary/lib/libfimg.so:system/lib/libfimg.so \
    vendor/samsung/kminilte/proprietary/lib/libmpp.so:system/lib/libmpp.so \
    vendor/samsung/kminilte/proprietary/lib/libhwcutilsmodule.so:system/lib/libhwcutilsmodule.so \
    vendor/samsung/kminilte/proprietary/lib/libvirtualdisplay.so:system/lib/libvirtualdisplay.so \
    vendor/samsung/kminilte/proprietary/lib/hw/consumerir.default.so:system/lib/hw/consumerir.default.so \
    vendor/samsung/kminilte/proprietary/vendor/lib/hw/keystore.exynos3.so:system/vendor/lib/hw/keystore.exynos3.so \
    vendor/samsung/kminilte/proprietary/vendor/lib/hw/lights.exynos3.so:system/vendor/lib/hw/lights.exynos3.so \
    vendor/samsung/kminilte/proprietary/bin/lpm:system/bin/lpm \
    vendor/samsung/kminilte/proprietary/lib/libmaet.so:system/lib/libmaet.so \
    vendor/samsung/kminilte/proprietary/lib/libsxqk_skia.so:system/lib/libsxqk_skia.so \
    vendor/samsung/kminilte/proprietary/media/wireless_left.spi:system/media/wireless_left.spi \
    vendor/samsung/kminilte/proprietary/media/wireless_right.spi:system/media/wireless_right.spi \
    vendor/samsung/kminilte/proprietary/media/battery_cover.spi:system/media/battery_cover.spi \
    vendor/samsung/kminilte/proprietary/media/battery_error.spi:system/media/battery_error.spi \
    vendor/samsung/kminilte/proprietary/media/particle_intro.spi:system/media/particle_intro.spi \
    vendor/samsung/kminilte/proprietary/media/particle_loop.spi:system/media/particle_loop.spi \
    vendor/samsung/kminilte/proprietary/media/lcd_density.txt:system/media/lcd_density.txt \
    vendor/samsung/kminilte/proprietary/media/percentage.spi:system/media/percentage.spi \
    vendor/samsung/kminilte/proprietary/media/battery_temperature_error.spi:system/media/battery_temperature_error.spi \
    vendor/samsung/kminilte/proprietary/media/battery_low.spi:system/media/battery_low.spi \
    vendor/samsung/kminilte/proprietary/media/wave_loop.spi:system/media/wave_loop.spi \
    vendor/samsung/kminilte/proprietary/media/incompatible_charger.spi:system/media/incompatible_charger.spi \
    vendor/samsung/kminilte/proprietary/media/battery_temperature_limit.spi:system/media/battery_temperature_limit.spi \
    vendor/samsung/kminilte/proprietary/vendor/firmware/fimc_is_fw2.bin:system/vendor/firmware/fimc_is_fw2.bin \
    vendor/samsung/kminilte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/kminilte/proprietary/vendor/firmware/setfile_4h5.bin:system/vendor/firmware/setfile_4h5.bin \
    vendor/samsung/kminilte/proprietary/vendor/firmware/setfile_6a3.bin:system/vendor/firmware/setfile_6a3.bin \
    vendor/samsung/kminilte/proprietary/vendor/firmware/setfile_6b2.bin:system/vendor/firmware/setfile_6b2.bin \
    vendor/samsung/kminilte/proprietary/lib/hw/nfc_nci.universal3470.so:system/lib/hw/nfc_nci.universal3470.so \
    vendor/samsung/kminilte/proprietary/etc/sec_s3fwrn5_rfreg.bin:system/etc/sec_s3fwrn5_rfreg.bin \
    vendor/samsung/kminilte/proprietary/vendor/firmware/sec_s3fwrn5_firmware.bin:system/vendor/firmware/sec_s3fwrn5_firmware.bin \
    vendor/samsung/kminilte/proprietary/etc/init.sec.boot.sh:system/etc/init.sec.boot.sh \
    vendor/samsung/kminilte/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/kminilte/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/02010000080300030000000000000000.tlbin:system/app/mcRegistry/02010000080300030000000000000000.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/03010000080300030000000000000000.tlbin:system/app/mcRegistry/03010000080300030000000000000000.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff000000000000000000000009.tlbin:system/app/mcRegistry/ffffffff000000000000000000000009.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffff000000000000000000000018.tlbin:system/app/mcRegistry/ffffffff000000000000000000000018.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/kminilte/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/kminilte/proprietary/lib/libgdmcprov.so:system/lib/libgdmcprov.so \
    vendor/samsung/kminilte/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
    vendor/samsung/kminilte/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
    vendor/samsung/kminilte/proprietary/etc/ExynosOMXReg.conf:system/etc/ExynosOMXReg.conf \
    vendor/samsung/kminilte/proprietary/lib/libExynosOMX263d.so:system/lib/libExynosOMX263d.so \
    vendor/samsung/kminilte/proprietary/lib/libExynosOMX264d.so:system/lib/libExynosOMX264d.so \
    vendor/samsung/kminilte/proprietary/lib/libExynosOMXCmn.so:system/lib/libExynosOMXCmn.so \
    vendor/samsung/kminilte/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/samsung/kminilte/proprietary/lib/libExynosOMXCore.so:system/lib/libExynosOMXCore.so \
    vendor/samsung/kminilte/proprietary/lib/libExynosOMXMp4vd.so:system/lib/libExynosOMXMp4vd.so \
    vendor/samsung/kminilte/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
    vendor/samsung/kminilte/proprietary/lib/libExynosOMXVc1d.so:system/lib/libExynosOMXVc1d.so \
    vendor/samsung/kminilte/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/kminilte/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/kminilte/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/kminilte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/kminilte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/kminilte/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/kminilte/proprietary/etc/plmn_delta.bin:system/etc/plmn_delta.bin \
    vendor/samsung/kminilte/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    vendor/samsung/kminilte/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/kminilte/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/kminilte/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/kminilte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/kminilte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/kminilte/proprietary/lib/hw/sensors.universal3470.so:system/lib/hw/sensors.universal3470.so \
    vendor/samsung/kminilte/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
    vendor/samsung/kminilte/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/samsung/kminilte/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
    vendor/samsung/kminilte/proprietary/lib/libacdapi_clb.so:system/lib/libacdapi_clb.so \
    vendor/samsung/kminilte/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/kminilte/proprietary/etc/wifi/bcmdhd_apsta.bin_b2:system/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/kminilte/proprietary/etc/wifi/bcmdhd_p2p.bin_b2:system/etc/wifi/bcmdhd_p2p.bin_b2 \
    vendor/samsung/kminilte/proprietary/etc/wifi/bcmdhd_sta.bin_b2:system/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/kminilte/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt
